prod:
  image: vizzuality/nex-gddp:1.0.0${STAGING}
  ports:
    - "3078"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: nex-gddp${STAGING}
